apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
#  annotations:
#      prometheus.io/scrape: {{ .Values.annotations.scrape }}
#      prometheus.io/path: {{ .Values.annotations.path }}
#      prometheus.io/port: {{ .Values.annotations.port }}
spec:
  selector: 
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.nodePort }}
